spring:
  datasource:
    url: jdbc:mysql://xxx:xxx/xxx?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: dbuser
    password: dbuserDev123
  jpa:
    hibernate:
      ddl-auto: update